sudo: required

services:
  - docker

before_install:
  - docker pull python:2-alpine3.6
  - docker pull python:3-alpine3.6

script:
  - docker build -t python2/3.1 ./python2/3.1.0/
  - docker build -t python2/3.2 ./python2/3.2.0/
  - docker build -t python2/3.3 ./python2/3.3.0/
  - docker build -t python3/3.1 ./python3/3.1.0/
  - docker build -t python3/3.2 ./python3/3.2.0/
  - docker build -t python3/3.3 ./python3/3.3.0/
