sudo: required

language: ruby

services:
  - docker

before_install:
  - docker pull python:2-alpine3.6
  - docker pull python:3-alpine3.6

script:
  - docker build -t python2/3.1 ./python2/3.1.0/
  - docker build -t python2/3.1 ./python2/3.1.0/
  - docker build -t python2/3.1 ./python2/3.1.0/
  - docker build -t python2/3.1 ./python2/3.1.0/
